apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment_and_service.yaml
  - ocr-deployment-and-service.yaml
  - redis-deployment-and-service.yaml
  - db-secret.yaml
  - service-monitor.yaml

# Filter out the old dashboard/monitoring files as we're moving to Helm
# - gf-config.yaml
# - monitoring.yaml
